/**
 * Copyright (c) 2015 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package utils;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.slf4j.Logger;

import java.util.ArrayList;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class LoggingArrayList<T> extends ArrayList<T> {
  Logger logger;
  ObjectMapper mapper;

  public LoggingArrayList(Logger logger){
    this.logger = logger;
    this.mapper = new ObjectMapper();
  }

  @Override
  public boolean add(T e){
    try {
      logger.info(mapper.writeValueAsString(e));
    } catch (JsonProcessingException e1) {
      logger.error(e1.toString());
    }
    return super.add(e);
  }

}
