/**
 * Copyright (c) 2015 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not  use this file except  in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io;

import com.google.cloud.dataflow.sdk.transforms.DoFnTester;

import com.firebase.client.Firebase;

import java.util.AbstractMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class ChildMovedTest extends FirebaseChildTest {

  Entry<String, Entry<Object, Object>>[] withPriority;
  Entry<String, Entry<Object, Object>>[] shuffle;

  /* (non-Javadoc)
   * @see io.BaseFirebaseSourceTest#triggerEvents()
   */
  @Override
  public void triggerEvents(Firebase f) {
    @SuppressWarnings("deprecation")
    DoFnTester<Entry<String, Entry<Object, Object>>, Void> setWithPriority =
        DoFnTester.of(new DoFirebaseSetWithPriority(f.toString(), auther));

    setWithPriority.processBatch(withPriority);
    setWithPriority.processBatch(shuffle);

  }

  /* (non-Javadoc)
   * @see io.BaseFirebaseSourceTest#prepareData(java.util.List)
   */
  @SuppressWarnings("unchecked")
  @Override
  public void prepareData(List<Map<String, Object>> testData) {
    Set<Entry<String, Object>> entrySet = testData.get(0).entrySet();

    withPriority = new Entry[entrySet.size()];
    shuffle = new Entry[entrySet.size()];

    int i = 0;
    for (Entry<String, Object> entry : entrySet){
      withPriority[i] = new AbstractMap.SimpleImmutableEntry<String, Entry<Object, Object>>(
          entry.getKey(),
          new AbstractMap.SimpleImmutableEntry<Object, Object>(
              entry.getValue(),
              String.valueOf(i)));
      shuffle[i] = new AbstractMap.SimpleImmutableEntry<String, Entry<Object, Object>>(
          entry.getKey(),
          new AbstractMap.SimpleImmutableEntry<Object, Object>(
              entry.getValue(),
              String.valueOf((i + 1) % entrySet.size())));
      i++;
    }

  }

}
