/**
 * Copyright (c) 2015 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not  use this file except  in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io;

import com.google.cloud.dataflow.sdk.transforms.DoFnTester;

import com.firebase.client.Firebase;

import java.util.AbstractMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class ChildRemovedTest extends FirebaseChildTest {

  Entry<String, Object>[] someData;
  Entry<String, Object>[] nulls;

  /* (non-Javadoc)
   * @see io.BaseFirebaseSourceTest#prepareData(java.util.List)
   */
  @SuppressWarnings("unchecked")
  @Override
  public void prepareData(List<Map<String, Object>> testData) {
    Set<Entry<String, Object>> entrySet = testData.get(0).entrySet();
    someData = entrySet.toArray(new Entry[entrySet.size()]);

    nulls = new Entry[entrySet.size()];
    int i = 0;
    for (Entry<String, Object> entry : entrySet){
      logger.info(entry.getKey());
      nulls[i] = new AbstractMap.SimpleImmutableEntry<String, Object>(entry.getKey(), null);
      i++;
    }
  }

  /* (non-Javadoc)
   * @see io.BaseFirebaseSourceTest#triggerEvents()
   */
  @Override
  public void triggerEvents(Firebase f) {
    DoFnTester<Entry<String, Object>, Void> setter = DoFnTester.of(
        new DoFirebaseSet(f.toString(), auther));
    setter.processBatch(someData);
    setter.processBatch(nulls);
  }
}
