/**
 * Copyright (c) 2015 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not  use this file except  in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io;
import com.google.api.client.repackaged.com.google.common.base.Preconditions;
import com.google.cloud.dataflow.sdk.coders.Coder;
import com.google.cloud.dataflow.sdk.io.UnboundedSource;
import com.google.cloud.dataflow.sdk.options.PipelineOptions;
import com.google.cloud.dataflow.sdk.values.TypeDescriptor;

import com.firebase.client.AuthData;
import com.firebase.client.ChildEventListener;
import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.Firebase.CompletionListener;
import com.firebase.client.FirebaseError;
import com.firebase.client.FirebaseException;
import com.firebase.client.Query;
import com.firebase.client.ServerValue;
import com.firebase.client.ValueEventListener;

import org.joda.time.Instant;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.concurrent.Semaphore;
import java.util.concurrent.TimeUnit;

import javax.annotation.Nullable;

import events.ChildAdded;
import events.ChildChanged;
import events.ChildMoved;
import events.ChildRemoved;
import events.FirebaseEvent;
import events.ValueChanged;

import utils.FirebaseAuthenticator;
import utils.FirebaseCheckpoint;
import utils.FirebaseCheckpointCoder;
import utils.FirebaseEventCoder;
import utils.Record;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class FirebaseSource<T>
  extends UnboundedSource<FirebaseEvent<T>, FirebaseCheckpoint<T>> {

  private static final long serialVersionUID = 5926529400127617094L;

  /**
   * Uses {@link FirebaseCheckpoint} to build a priority queue based on event time, for events
   * triggered by listeners specified in {@link FirebaseSource} construction.
   **/
  public class FirebaseReader extends UnboundedReader<FirebaseEvent<T>>{

    private final FirebaseSource<T> source;
    private final MessageDigest digest;
    private final Firebase timestampRef;
    private final FirebaseCheckpoint<T> checkpoint;
    private ValueEventListener valueListener;
    private ChildEventListener childListener;
    private FirebaseError error = null;

    public FirebaseReader(
        FirebaseSource<T> source,
        FirebaseCheckpoint<T> checkpoint) throws NoSuchAlgorithmException{
      this.source = source;
      this.digest = MessageDigest.getInstance("MD5");
      if (checkpoint == null){
        this.checkpoint = new FirebaseCheckpoint<T>();
      } else {
        this.checkpoint = checkpoint.reset();
      }
      this.valueListener = makeValueListener();
      this.childListener = makeChildListener();
      this.timestampRef = this.source.query.getRef().getRoot().child(
          Integer.toHexString(this.hashCode()) + Long.toHexString(System.currentTimeMillis()));
    }

    private ValueEventListener makeValueListener() {
      return new ValueEventListener(){

        @Override
        public void onCancelled(FirebaseError err) {
          error = err;
        }

        @Override
        public void onDataChange(DataSnapshot snapshot) {
          wrapEventWithInstant(new ValueChanged<T>(
              snapshot));
        }
      };
    }

    private ChildEventListener makeChildListener() {
      return new ChildEventListener(){
        @Override
        public void onCancelled(FirebaseError err) {
          error = err;
        }

        @Override
        public void onChildAdded(DataSnapshot snapshot, String previousChildName) {
          wrapEventWithInstant(new ChildAdded<T>(
              snapshot,
              previousChildName));
        }

        @Override
        public void onChildChanged(DataSnapshot snapshot, String previousChildName) {
          wrapEventWithInstant(new ChildChanged<T>(
              snapshot,
              previousChildName));
        }

        @Override
        public void onChildMoved(DataSnapshot snapshot, String previousChildName) {
          wrapEventWithInstant(new ChildMoved<T>(
              snapshot,
              previousChildName));
        }

        @Override
        public void onChildRemoved(DataSnapshot snapshot) {
          wrapEventWithInstant(new ChildRemoved<T>(
              snapshot));
        }
      };
    }

    /**
     * On receiving an event, {@link FirebaseReader} sets the {@link ServerValue#TIMESTAMP}
     * in the Firebase which will be populated with the current server time. This will trigger
     * a value change event, which can be used to retrieve a timestamp. Effectively this method
     * delegates dealing with clock drift between shards to the Firebase servers. Since events are
     * always processed in order by a single client, timestamps will be in the order events were
     * recieved.
     * @param event {@link FirebaseEvent} to wrap
     */
    private void wrapEventWithInstant(final FirebaseEvent<T> event){
      timestampRef.setValue(ServerValue.TIMESTAMP, new CompletionListener(){
        @Override
        public void onComplete(FirebaseError err, Firebase ref) {
          if (err != null){
            error = err;
          }
          ref.addListenerForSingleValueEvent(new ValueEventListener(){
            @Override
            public void onCancelled(FirebaseError err) {
              error = err;
            }
            @Override
            public void onDataChange(DataSnapshot timestamp) {
              checkpoint.put(new Record<T>(
                  new Instant(timestamp.getValue(Long.class)),
                  event));
            }
          });
        }
      });
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.UnboundedSource.UnboundedReader#advance()
     **/
    @Override
    public boolean advance() throws IOException {
      if (error == null){
        return this.checkpoint.advance();
      }
      throw error.toException();
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.UnboundedSource.UnboundedReader#getCheckpointMark()
     **/
    @Override
    public CheckpointMark getCheckpointMark() {
      return checkpoint;
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.UnboundedSource.UnboundedReader#getCurrentRecordId()
     **/
    @Override
    public byte[] getCurrentRecordId() throws NoSuchElementException {
      return digest.digest(
          ByteBuffer.allocate(12).putInt(
              this.checkpoint.read().data.hashCode()).putLong(
                  this.checkpoint.read().timestamp.getMillis()).array());
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.UnboundedSource.UnboundedReader#getCurrentSource()
     **/
    @Override
    public UnboundedSource<FirebaseEvent<T>, ?> getCurrentSource() {
      return this.source;
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.UnboundedSource.UnboundedReader#getWatermark()
     **/
    @Override
    public Instant getWatermark() {
      return this.checkpoint.minTimestamp();
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.UnboundedSource.UnboundedReader#start()
     **/
    @Override
    public boolean start() throws IOException {
      try {
        this.source.auther.authenticate(this.source.query.getRef());
      } catch (Exception e) {
        throw new IOException(e);
      }
      if (this.source.listenForChildEvents){
        this.childListener = this.source.query.addChildEventListener(this.childListener);
      }
      if (this.source.listenForValueEvents){
        this.valueListener = this.source.query.addValueEventListener(this.valueListener);
      }
      return this.advance();
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.Source.Reader#close()
     **/
    @Override
    public void close() throws IOException {
      if (this.source.listenForChildEvents) {
        this.source.query.removeEventListener(this.childListener);
      }
      if (this.source.listenForValueEvents){
        this.source.query.removeEventListener(this.valueListener);
      }
      final Semaphore lock = new Semaphore(1);
      try {
        lock.acquire();
      } catch (InterruptedException e) {
        throw new IOException(e);
      }
      timestampRef.removeValue(new CompletionListener(){

        @Override
        public void onComplete(FirebaseError err, Firebase arg1) {
          lock.release();
          if (err != null){
            throw err.toException();
          }
        }
      });
      try {
        lock.tryAcquire(Long.MAX_VALUE, TimeUnit.DAYS);
      } catch (InterruptedException e) {
        throw new IOException(e);
      }
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.Source.Reader#getCurrent()
     **/
    @Override
    public FirebaseEvent<T> getCurrent() throws NoSuchElementException {
      if (this.checkpoint.read() == null){
        throw new NoSuchElementException();
      }
      return this.checkpoint.read().data;
    }

    /**
     * @see com.google.cloud.dataflow.sdk.io.Source.Reader#getCurrentTimestamp()
     **/
    @Override
    public Instant getCurrentTimestamp() throws NoSuchElementException {
      if (this.checkpoint.read() == null){
        throw new NoSuchElementException();
      }
      return this.checkpoint.read().timestamp;
    }
  }

  private final Query query;
  private final FirebaseAuthenticator auther;
  private final boolean listenForChildEvents;
  private final boolean listenForValueEvents;
  private final Class<T> clazz;

  public static <K> FirebaseSource<K> childListenerOf(
      Class<K> clazz,
      FirebaseAuthenticator auther,
      Query query){
    return new FirebaseSource<K>(clazz, auther, query, true, false);
  }

  public static <K> FirebaseSource<K> valueListenerOf(
      Class<K> clazz,
      FirebaseAuthenticator auther,
      Query query){
    return new FirebaseSource<K>(clazz, auther, query, false, true);
  }



  public static <K> FirebaseSource<K> of(
      Class<K> clazz,
      FirebaseAuthenticator auther,
      Query query){
    return new FirebaseSource<K>(clazz, auther, query, true, true);
  }

  /**
   * @param clazz Class Reference for the type to deserialize {@link DataSnapshot}s into.
   * @param auther Authenticator
   * @param query Any {@link Query} reference.
   * @param listenForChildEvents Adds a {@link ChildEventListener} during runtime
   * @param listenForValueEvents Adds a {@link ValueEventListener} during runtime
   */
  protected FirebaseSource(
      Class<T> clazz,
      FirebaseAuthenticator auther,
      Query query,
      boolean listenForChildEvents,
      boolean listenForValueEvents){
    if (query.toString().equals(query.getRef().getRoot().toString())){
      throw new IllegalArgumentException("Cannot use a reference to the root of a Firebase "
          + "repository. Since FirebaseSource uses a ref at the root of the repository to store"
          + "timestamps, this will result in an endless event loop, which will livelock your"
          + "pipeline.");
    }
    this.clazz = clazz;
    this.auther = auther;
    this.query = query;
    this.listenForChildEvents = listenForChildEvents;
    this.listenForValueEvents = listenForValueEvents;
  }

  /**
   * @see UnboundedSource#generateInitialSplits(int, PipelineOptions)
   **/
  @SuppressWarnings("unchecked")
  @Override
  public List<? extends UnboundedSource<FirebaseEvent<T>, FirebaseCheckpoint<T>>>
    generateInitialSplits(
      int numSplits, PipelineOptions arg1) throws Exception {
    return Arrays.asList(this);
  }

  /**
   * @see com.google.cloud.dataflow.sdk.io.Source#getDefaultOutputCoder()
   **/
  @Override
  public Coder<FirebaseEvent<T>> getDefaultOutputCoder() {
    return FirebaseEventCoder.of(new TypeDescriptor<FirebaseEvent<T>>(){}, this.clazz);
  }

  /**
   * @see com.google.cloud.dataflow.sdk.io.Source#validate()
   **/
  @Override
  public void validate() {

    AuthData result;

    try {
      result = auther.authenticate(query.getRef());
    } catch (FirebaseException e) {
      result = null;
      e.printStackTrace();
    } catch (InterruptedException e) {
      result = null;
      e.printStackTrace();
    }

    Preconditions.checkNotNull(result);
  }

  @Override
  public UnboundedReader<FirebaseEvent<T>> createReader(
      PipelineOptions arg0, @Nullable FirebaseCheckpoint<T> arg1) {
    try {
      return new FirebaseReader(this, arg1);
    } catch (NoSuchAlgorithmException e) {
      e.printStackTrace();
    }
    return null;
  }

  @Override
  public Coder<FirebaseCheckpoint<T>> getCheckpointMarkCoder() {
    return FirebaseCheckpointCoder.of(new TypeDescriptor<FirebaseCheckpoint<T>>(){}, this.clazz);
  }

}
